package com.avito.android.validation;

import com.avito.android.items.BasicInputItem;
import com.avito.android.items.RangeItem;
import com.avito.android.remote.model.category_parameters.ParametersTree;
import io.reactivex.Maybe;
import io.reactivex.Observable;
import io.reactivex.Single;
import java.util.List;
import java.util.Map;
import kotlin.Metadata;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
@Metadata(bv = {1, 0, 3}, d1 = {"\u0000\\\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\u0010 \n\u0002\u0018\u0002\n\u0002\b\u0004\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0004\n\u0002\u0010\u000b\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\b\u0004\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010$\n\u0002\b\u0003\bf\u0018\u00002\u00020\u0001J!\u0010\u0007\u001a\u00020\u00062\u0006\u0010\u0003\u001a\u00020\u00022\b\u0010\u0005\u001a\u0004\u0018\u00010\u0004H&¢\u0006\u0004\b\u0007\u0010\bJ-\u0010\f\u001a\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u000b0\n0\t2\u0006\u0010\u0003\u001a\u00020\u00022\b\u0010\u0005\u001a\u0004\u0018\u00010\u0004H&¢\u0006\u0004\b\f\u0010\rJ#\u0010\u000e\u001a\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u000b0\n0\t2\u0006\u0010\u0003\u001a\u00020\u0002H&¢\u0006\u0004\b\u000e\u0010\u000fJ\u001d\u0010\u0011\u001a\b\u0012\u0004\u0012\u00020\u00020\u00102\u0006\u0010\u0003\u001a\u00020\u0002H&¢\u0006\u0004\b\u0011\u0010\u0012J\u001b\u0010\u0014\u001a\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u000b0\n0\u0013H&¢\u0006\u0004\b\u0014\u0010\u0015J\u001b\u0010\u0016\u001a\u000e\u0012\n\u0012\b\u0012\u0004\u0012\u00020\u000b0\n0\tH&¢\u0006\u0004\b\u0016\u0010\u0017J\u001f\u0010\u001a\u001a\u00020\u00062\u0006\u0010\u0003\u001a\u00020\u00022\u0006\u0010\u0019\u001a\u00020\u0018H&¢\u0006\u0004\b\u001a\u0010\u001bJ#\u0010\u001f\u001a\u00020\u00062\u0006\u0010\u001d\u001a\u00020\u001c2\n\b\u0002\u0010\u001e\u001a\u0004\u0018\u00010\u001cH&¢\u0006\u0004\b\u001f\u0010 J\u001f\u0010#\u001a\u00020\u00062\u0006\u0010\u0003\u001a\u00020\u00022\u0006\u0010\"\u001a\u00020!H&¢\u0006\u0004\b#\u0010$J#\u0010&\u001a\u000e\u0012\u0004\u0012\u00020\u0002\u0012\u0004\u0012\u00020\u00020%2\u0006\u0010\u0003\u001a\u00020\u0002H&¢\u0006\u0004\b&\u0010'¨\u0006("}, d2 = {"Lcom/avito/android/validation/ParametersListInteractor;", "", "", "id", "Lcom/avito/android/items/BasicInputItem;", "valueItem", "", "applyNewValue", "(Ljava/lang/String;Lcom/avito/android/items/BasicInputItem;)V", "Lio/reactivex/Single;", "", "Lcom/avito/android/validation/ValidationResult;", "validateWithDependentEntitiesAndApplyValue", "(Ljava/lang/String;Lcom/avito/android/items/BasicInputItem;)Lio/reactivex/Single;", "validateWithDependentEntities", "(Ljava/lang/String;)Lio/reactivex/Single;", "Lio/reactivex/Maybe;", "getHintFor", "(Ljava/lang/String;)Lio/reactivex/Maybe;", "Lio/reactivex/Observable;", "getInitialValidationResults", "()Lio/reactivex/Observable;", "validateWholeStructure", "()Lio/reactivex/Single;", "", "checked", "applyToggleValue", "(Ljava/lang/String;Z)V", "Lcom/avito/android/remote/model/category_parameters/ParametersTree;", "paramsToValidate", "paramsForConditionChecks", "setParameters", "(Lcom/avito/android/remote/model/category_parameters/ParametersTree;Lcom/avito/android/remote/model/category_parameters/ParametersTree;)V", "Lcom/avito/android/items/RangeItem;", "item", "applyRangeValue", "(Ljava/lang/String;Lcom/avito/android/items/RangeItem;)V", "", "processAutogeneratedValues", "(Ljava/lang/String;)Ljava/util/Map;", "item-temporary_release"}, k = 1, mv = {1, 4, 2})
public interface ParametersListInteractor {

    @Metadata(bv = {1, 0, 3}, d1 = {}, d2 = {}, k = 3, mv = {1, 4, 2})
    public static final class DefaultImpls {
        public static /* synthetic */ void setParameters$default(ParametersListInteractor parametersListInteractor, ParametersTree parametersTree, ParametersTree parametersTree2, int i, Object obj) {
            if (obj == null) {
                if ((i & 2) != 0) {
                    parametersTree2 = null;
                }
                parametersListInteractor.setParameters(parametersTree, parametersTree2);
                return;
            }
            throw new UnsupportedOperationException("Super calls with default arguments not supported in this target, function: setParameters");
        }
    }

    void applyNewValue(@NotNull String str, @Nullable BasicInputItem basicInputItem);

    void applyRangeValue(@NotNull String str, @NotNull RangeItem rangeItem);

    void applyToggleValue(@NotNull String str, boolean z);

    @NotNull
    Maybe<String> getHintFor(@NotNull String str);

    @NotNull
    Observable<List<ValidationResult>> getInitialValidationResults();

    @NotNull
    Map<String, String> processAutogeneratedValues(@NotNull String str);

    void setParameters(@NotNull ParametersTree parametersTree, @Nullable ParametersTree parametersTree2);

    @NotNull
    Single<List<ValidationResult>> validateWholeStructure();

    @NotNull
    Single<List<ValidationResult>> validateWithDependentEntities(@NotNull String str);

    @NotNull
    Single<List<ValidationResult>> validateWithDependentEntitiesAndApplyValue(@NotNull String str, @Nullable BasicInputItem basicInputItem);
}
