package com.avito.android.autogenerated_value;

import kotlin.Metadata;
import kotlin.Unit;
import kotlin.jvm.functions.Function2;
import org.jetbrains.annotations.NotNull;
@Metadata(bv = {1, 0, 3}, d1 = {"\u0000&\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0002\u0010\u000e\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\r\n\u0000\n\u0002\u0010\u0002\n\u0002\b\u0004\bf\u0018\u00002\u00020\u0001JQ\u0010\u000b\u001a\u00020\t2\u0006\u0010\u0003\u001a\u00020\u000228\u0010\n\u001a4\u0012\u0013\u0012\u00110\u0002¢\u0006\f\b\u0005\u0012\b\b\u0006\u0012\u0004\b\b(\u0003\u0012\u0015\u0012\u0013\u0018\u00010\u0007¢\u0006\f\b\u0005\u0012\b\b\u0006\u0012\u0004\b\b(\b\u0012\u0004\u0012\u00020\t0\u0004H&¢\u0006\u0004\b\u000b\u0010\f¨\u0006\r"}, d2 = {"Lcom/avito/android/autogenerated_value/AutogeneratedValueParametersInteractor;", "", "", "id", "Lkotlin/Function2;", "Lkotlin/ParameterName;", "name", "", "generatedValue", "", "callback", "onValueChanged", "(Ljava/lang/String;Lkotlin/jvm/functions/Function2;)V", "item-temporary_release"}, k = 1, mv = {1, 4, 2})
public interface AutogeneratedValueParametersInteractor {
    void onValueChanged(@NotNull String str, @NotNull Function2<? super String, ? super CharSequence, Unit> function2);
}
