package ru.sravni.android.bankproduct.repository.dictionary;

import com.avito.android.remote.auth.AuthSource;
import java.util.HashMap;
import kotlin.Metadata;
import kotlin.TuplesKt;
import ru.sravni.android.bankproduct.domain.dictionary.entity.ProductDictionaryInfoDomain;
import ru.sravni.android.bankproduct.utils.product.ProductUtilKt;
import t6.n.r;
@Metadata(bv = {1, 0, 3}, d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0002\u0010\u000e\n\u0002\u0018\u0002\n\u0002\b\u0004\"\u0016\u0010\u0003\u001a\u00020\u00008\u0002@\u0002X\u0004¢\u0006\u0006\n\u0004\b\u0001\u0010\u0002\"2\u0010\t\u001a\u001e\u0012\u0004\u0012\u00020\u0005\u0012\u0004\u0012\u00020\u00000\u0004j\u000e\u0012\u0004\u0012\u00020\u0005\u0012\u0004\u0012\u00020\u0000`\u00068\u0002@\u0002X\u0004¢\u0006\u0006\n\u0004\b\u0007\u0010\b¨\u0006\n"}, d2 = {"Lru/sravni/android/bankproduct/domain/dictionary/entity/ProductDictionaryInfoDomain;", AuthSource.BOOKING_ORDER, "Lru/sravni/android/bankproduct/domain/dictionary/entity/ProductDictionaryInfoDomain;", "unknownProduct", "Ljava/util/HashMap;", "", "Lkotlin/collections/HashMap;", AuthSource.SEND_ABUSE, "Ljava/util/HashMap;", "dictionary", "sravnichat_release"}, k = 2, mv = {1, 4, 0})
public final class ProductNameDictionaryKt {
    public static final HashMap<String, ProductDictionaryInfoDomain> a = r.hashMapOf(TuplesKt.to(ProductUtilKt.getCREDIT_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getCREDIT_CHAT_NAME(), "Подбор\nкредита", "Подбор кредита")), TuplesKt.to(ProductUtilKt.getOSAGO_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getOSAGO_CHAT_NAME(), "E-ОСАГО", "ОСАГО")), TuplesKt.to(ProductUtilKt.getKASKO_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getKASKO_CHAT_NAME(), "Каско", "КАСКО")), TuplesKt.to(ProductUtilKt.getMORTRAGE_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getMORTRAGE_CHAT_NAME(), "Ипотека", "Ипотека")), TuplesKt.to(ProductUtilKt.getDEPOSIT_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getDEPOSIT_CHAT_NAME(), "Вклады", "Вклады")), TuplesKt.to(ProductUtilKt.getDEBIT_CARDS_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getDEBIT_CARDS_CHAT_NAME(), "Дебетовые\nкарты", "Дебетовые карты")), TuplesKt.to(ProductUtilKt.getTRAVEL_INSURANCE_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getTRAVEL_INSURANCE_CHAT_NAME(), "Страхование\nпутешествий", "ВЗР")), TuplesKt.to(ProductUtilKt.getPROPERTY_INSURANSE_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getPROPERTY_INSURANSE_CHAT_NAME(), "Страхование\nнедвижимости", "Страхование недвижимости")), TuplesKt.to(ProductUtilKt.getMORTRAGE_INSURANSE_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getMORTRAGE_INSURANSE_CHAT_NAME(), "Страхование\nипотеки", "Страхование ипотеки")), TuplesKt.to(ProductUtilKt.getCREDIT_RATING_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getCREDIT_RATING_CHAT_NAME(), "Кредитный\nрейтинг", "Кредитный рейтинг")), TuplesKt.to(ProductUtilKt.getCREDIT_AVITO_CHAT_NAME(), new ProductDictionaryInfoDomain(ProductUtilKt.getCREDIT_AVITO_CHAT_NAME(), "Подбор\nкредита", "Подбор кредита АВИТО")));
    public static final ProductDictionaryInfoDomain b = new ProductDictionaryInfoDomain("", "", "unknownProduct");
}
