package com.avito.android.remote.model.category_parameters;

import android.os.Parcel;
import android.os.Parcelable;
import com.avito.android.remote.model.Navigation;
import com.google.gson.annotations.SerializedName;
import java.util.LinkedHashMap;
import java.util.Map;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.parcelize.Parcelize;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import t6.r.a.j;
@Parcelize
@Metadata(bv = {1, 0, 3}, d1 = {"\u00000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\b\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0010$\n\u0002\u0010\u000e\n\u0002\u0018\u0002\n\u0002\b\f\b\u0007\u0018\u00002\u00020\u0001:\u0001\u0018B+\u0012\n\b\u0002\u0010\u0012\u001a\u0004\u0018\u00010\f\u0012\u0016\b\u0002\u0010\u000e\u001a\u0010\u0012\u0004\u0012\u00020\f\u0012\u0004\u0012\u00020\r\u0018\u00010\u000b¢\u0006\u0004\b\u0016\u0010\u0017J\u0010\u0010\u0003\u001a\u00020\u0002HÖ\u0001¢\u0006\u0004\b\u0003\u0010\u0004J \u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002HÖ\u0001¢\u0006\u0004\b\t\u0010\nR*\u0010\u000e\u001a\u0010\u0012\u0004\u0012\u00020\f\u0012\u0004\u0012\u00020\r\u0018\u00010\u000b8\u0006@\u0007X\u0004¢\u0006\f\n\u0004\b\u000e\u0010\u000f\u001a\u0004\b\u0010\u0010\u0011R\u001e\u0010\u0012\u001a\u0004\u0018\u00010\f8\u0006@\u0007X\u0004¢\u0006\f\n\u0004\b\u0012\u0010\u0013\u001a\u0004\b\u0014\u0010\u0015¨\u0006\u0019"}, d2 = {"Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue;", "Landroid/os/Parcelable;", "", "describeContents", "()I", "Landroid/os/Parcel;", "parcel", "flags", "", "writeToParcel", "(Landroid/os/Parcel;I)V", "", "", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute;", Navigation.ATTRIBUTES, "Ljava/util/Map;", "getAttributes", "()Ljava/util/Map;", "pattern", "Ljava/lang/String;", "getPattern", "()Ljava/lang/String;", "<init>", "(Ljava/lang/String;Ljava/util/Map;)V", "Attribute", "models_release"}, k = 1, mv = {1, 4, 2})
public final class AutoGeneratedValue implements Parcelable {
    public static final Parcelable.Creator<AutoGeneratedValue> CREATOR = new Creator();
    @SerializedName(Navigation.ATTRIBUTES)
    @Nullable
    private final Map<String, Attribute> attributes;
    @SerializedName("pattern")
    @Nullable
    private final String pattern;

    @Metadata(bv = {1, 0, 3}, d1 = {"\u0000\u0016\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0004\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0000\b6\u0018\u00002\u00020\u0001:\u0002\u0004\u0005B\t\b\u0002¢\u0006\u0004\b\u0002\u0010\u0003\u0001\u0002\u0006\u0007¨\u0006\b"}, d2 = {"Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute;", "Landroid/os/Parcelable;", "<init>", "()V", "ParameterAttribute", "UnknownAttribute", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute$ParameterAttribute;", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute$UnknownAttribute;", "models_release"}, k = 1, mv = {1, 4, 2})
    public static abstract class Attribute implements Parcelable {

        @Parcelize
        @Metadata(bv = {1, 0, 3}, d1 = {"\u00000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\b\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0002\n\u0002\u0010\u000e\n\u0002\b\u0006\n\u0002\u0010\u000b\n\u0002\b\t\b\u0007\u0018\u00002\u00020\u0001B3\u0012\u0006\u0010\f\u001a\u00020\u000b\u0012\n\b\u0002\u0010\u0010\u001a\u0004\u0018\u00010\u000b\u0012\n\b\u0002\u0010\u0017\u001a\u0004\u0018\u00010\u000b\u0012\n\b\u0002\u0010\u0013\u001a\u0004\u0018\u00010\u0012¢\u0006\u0004\b\u0019\u0010\u001aJ\u0010\u0010\u0003\u001a\u00020\u0002HÖ\u0001¢\u0006\u0004\b\u0003\u0010\u0004J \u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002HÖ\u0001¢\u0006\u0004\b\t\u0010\nR\u001c\u0010\f\u001a\u00020\u000b8\u0006@\u0007X\u0004¢\u0006\f\n\u0004\b\f\u0010\r\u001a\u0004\b\u000e\u0010\u000fR\u001e\u0010\u0010\u001a\u0004\u0018\u00010\u000b8\u0006@\u0007X\u0004¢\u0006\f\n\u0004\b\u0010\u0010\r\u001a\u0004\b\u0011\u0010\u000fR\u001e\u0010\u0013\u001a\u0004\u0018\u00010\u00128\u0006@\u0007X\u0004¢\u0006\f\n\u0004\b\u0013\u0010\u0014\u001a\u0004\b\u0015\u0010\u0016R\u001e\u0010\u0017\u001a\u0004\u0018\u00010\u000b8\u0006@\u0007X\u0004¢\u0006\f\n\u0004\b\u0017\u0010\r\u001a\u0004\b\u0018\u0010\u000f¨\u0006\u001b"}, d2 = {"Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute$ParameterAttribute;", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute;", "", "describeContents", "()I", "Landroid/os/Parcel;", "parcel", "flags", "", "writeToParcel", "(Landroid/os/Parcel;I)V", "", "parameterId", "Ljava/lang/String;", "getParameterId", "()Ljava/lang/String;", "prefix", "getPrefix", "", "required", "Ljava/lang/Boolean;", "getRequired", "()Ljava/lang/Boolean;", "postfix", "getPostfix", "<init>", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/Boolean;)V", "models_release"}, k = 1, mv = {1, 4, 2})
        public static final class ParameterAttribute extends Attribute {
            public static final Parcelable.Creator<ParameterAttribute> CREATOR = new Creator();
            @SerializedName("fieldId")
            @NotNull
            private final String parameterId;
            @SerializedName("postfix")
            @Nullable
            private final String postfix;
            @SerializedName("prefix")
            @Nullable
            private final String prefix;
            @SerializedName("required")
            @Nullable
            private final Boolean required;

            @Metadata(bv = {1, 0, 3}, d1 = {}, d2 = {}, k = 3, mv = {1, 4, 2})
            public static class Creator implements Parcelable.Creator<ParameterAttribute> {
                @Override // android.os.Parcelable.Creator
                @NotNull
                public final ParameterAttribute createFromParcel(@NotNull Parcel parcel) {
                    Boolean bool;
                    Intrinsics.checkNotNullParameter(parcel, "in");
                    String readString = parcel.readString();
                    String readString2 = parcel.readString();
                    String readString3 = parcel.readString();
                    if (parcel.readInt() != 0) {
                        bool = Boolean.valueOf(parcel.readInt() != 0);
                    } else {
                        bool = null;
                    }
                    return new ParameterAttribute(readString, readString2, readString3, bool);
                }

                @Override // android.os.Parcelable.Creator
                @NotNull
                public final ParameterAttribute[] newArray(int i) {
                    return new ParameterAttribute[i];
                }
            }

            /* JADX INFO: this call moved to the top of the method (can break code semantics) */
            public /* synthetic */ ParameterAttribute(String str, String str2, String str3, Boolean bool, int i, j jVar) {
                this(str, (i & 2) != 0 ? null : str2, (i & 4) != 0 ? null : str3, (i & 8) != 0 ? null : bool);
            }

            @Override // android.os.Parcelable
            public int describeContents() {
                return 0;
            }

            @NotNull
            public final String getParameterId() {
                return this.parameterId;
            }

            @Nullable
            public final String getPostfix() {
                return this.postfix;
            }

            @Nullable
            public final String getPrefix() {
                return this.prefix;
            }

            @Nullable
            public final Boolean getRequired() {
                return this.required;
            }

            @Override // android.os.Parcelable
            public void writeToParcel(@NotNull Parcel parcel, int i) {
                boolean z;
                Intrinsics.checkNotNullParameter(parcel, "parcel");
                parcel.writeString(this.parameterId);
                parcel.writeString(this.prefix);
                parcel.writeString(this.postfix);
                Boolean bool = this.required;
                if (bool != null) {
                    parcel.writeInt(1);
                    z = bool.booleanValue();
                } else {
                    z = false;
                }
                int i2 = z ? 1 : 0;
                int i3 = z ? 1 : 0;
                int i4 = z ? 1 : 0;
                parcel.writeInt(i2);
            }

            /* JADX INFO: super call moved to the top of the method (can break code semantics) */
            public ParameterAttribute(@NotNull String str, @Nullable String str2, @Nullable String str3, @Nullable Boolean bool) {
                super(null);
                Intrinsics.checkNotNullParameter(str, "parameterId");
                this.parameterId = str;
                this.prefix = str2;
                this.postfix = str3;
                this.required = bool;
            }
        }

        @Parcelize
        @Metadata(bv = {1, 0, 3}, d1 = {"\u0000 \n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0010\b\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0002\b\u0005\bÇ\u0002\u0018\u00002\u00020\u0001B\t\b\u0002¢\u0006\u0004\b\u000b\u0010\fJ\u0010\u0010\u0003\u001a\u00020\u0002HÖ\u0001¢\u0006\u0004\b\u0003\u0010\u0004J \u0010\t\u001a\u00020\b2\u0006\u0010\u0006\u001a\u00020\u00052\u0006\u0010\u0007\u001a\u00020\u0002HÖ\u0001¢\u0006\u0004\b\t\u0010\n¨\u0006\r"}, d2 = {"Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute$UnknownAttribute;", "Lcom/avito/android/remote/model/category_parameters/AutoGeneratedValue$Attribute;", "", "describeContents", "()I", "Landroid/os/Parcel;", "parcel", "flags", "", "writeToParcel", "(Landroid/os/Parcel;I)V", "<init>", "()V", "models_release"}, k = 1, mv = {1, 4, 2})
        public static final class UnknownAttribute extends Attribute {
            public static final Parcelable.Creator<UnknownAttribute> CREATOR = new Creator();
            @NotNull
            public static final UnknownAttribute INSTANCE = new UnknownAttribute();

            @Metadata(bv = {1, 0, 3}, d1 = {}, d2 = {}, k = 3, mv = {1, 4, 2})
            public static class Creator implements Parcelable.Creator<UnknownAttribute> {
                @Override // android.os.Parcelable.Creator
                @NotNull
                public final UnknownAttribute createFromParcel(@NotNull Parcel parcel) {
                    Intrinsics.checkNotNullParameter(parcel, "in");
                    if (parcel.readInt() != 0) {
                        return UnknownAttribute.INSTANCE;
                    }
                    return null;
                }

                @Override // android.os.Parcelable.Creator
                @NotNull
                public final UnknownAttribute[] newArray(int i) {
                    return new UnknownAttribute[i];
                }
            }

            private UnknownAttribute() {
                super(null);
            }

            @Override // android.os.Parcelable
            public int describeContents() {
                return 0;
            }

            @Override // android.os.Parcelable
            public void writeToParcel(@NotNull Parcel parcel, int i) {
                Intrinsics.checkNotNullParameter(parcel, "parcel");
                parcel.writeInt(1);
            }
        }

        private Attribute() {
        }

        public /* synthetic */ Attribute(j jVar) {
            this();
        }
    }

    @Metadata(bv = {1, 0, 3}, d1 = {}, d2 = {}, k = 3, mv = {1, 4, 2})
    public static class Creator implements Parcelable.Creator<AutoGeneratedValue> {
        @Override // android.os.Parcelable.Creator
        @NotNull
        public final AutoGeneratedValue createFromParcel(@NotNull Parcel parcel) {
            LinkedHashMap linkedHashMap;
            Intrinsics.checkNotNullParameter(parcel, "in");
            String readString = parcel.readString();
            if (parcel.readInt() != 0) {
                int readInt = parcel.readInt();
                linkedHashMap = new LinkedHashMap(readInt);
                while (readInt != 0) {
                    linkedHashMap.put(parcel.readString(), (Attribute) parcel.readParcelable(AutoGeneratedValue.class.getClassLoader()));
                    readInt--;
                }
            } else {
                linkedHashMap = null;
            }
            return new AutoGeneratedValue(readString, linkedHashMap);
        }

        @Override // android.os.Parcelable.Creator
        @NotNull
        public final AutoGeneratedValue[] newArray(int i) {
            return new AutoGeneratedValue[i];
        }
    }

    public AutoGeneratedValue() {
        this(null, null, 3, null);
    }

    /* JADX DEBUG: Multi-variable search result rejected for r2v0, resolved type: java.util.Map<java.lang.String, ? extends com.avito.android.remote.model.category_parameters.AutoGeneratedValue$Attribute> */
    /* JADX WARN: Multi-variable type inference failed */
    public AutoGeneratedValue(@Nullable String str, @Nullable Map<String, ? extends Attribute> map) {
        this.pattern = str;
        this.attributes = map;
    }

    @Override // android.os.Parcelable
    public int describeContents() {
        return 0;
    }

    @Nullable
    public final Map<String, Attribute> getAttributes() {
        return this.attributes;
    }

    @Nullable
    public final String getPattern() {
        return this.pattern;
    }

    /* JADX WARN: Type inference failed for: r1v2, types: [java.util.Map$Entry, java.lang.Object] */
    /* JADX WARNING: Unknown variable types count: 1 */
    @Override // android.os.Parcelable
    /* Code decompiled incorrectly, please refer to instructions dump. */
    public void writeToParcel(@org.jetbrains.annotations.NotNull android.os.Parcel r4, int r5) {
        /*
            r3 = this;
            java.lang.String r0 = "parcel"
            kotlin.jvm.internal.Intrinsics.checkNotNullParameter(r4, r0)
            java.lang.String r0 = r3.pattern
            r4.writeString(r0)
            java.util.Map<java.lang.String, com.avito.android.remote.model.category_parameters.AutoGeneratedValue$Attribute> r0 = r3.attributes
            if (r0 == 0) goto L_0x0030
            r1 = 1
            java.util.Iterator r0 = a2.b.a.a.a.m0(r4, r1, r0)
        L_0x0013:
            boolean r1 = r0.hasNext()
            if (r1 == 0) goto L_0x0034
            java.lang.Object r1 = r0.next()
            java.lang.Object r2 = r1.getKey()
            java.lang.String r2 = (java.lang.String) r2
            r4.writeString(r2)
            java.lang.Object r1 = r1.getValue()
            com.avito.android.remote.model.category_parameters.AutoGeneratedValue$Attribute r1 = (com.avito.android.remote.model.category_parameters.AutoGeneratedValue.Attribute) r1
            r4.writeParcelable(r1, r5)
            goto L_0x0013
        L_0x0030:
            r5 = 0
            r4.writeInt(r5)
        L_0x0034:
            return
        */
        throw new UnsupportedOperationException("Method not decompiled: com.avito.android.remote.model.category_parameters.AutoGeneratedValue.writeToParcel(android.os.Parcel, int):void");
    }

    /* JADX INFO: this call moved to the top of the method (can break code semantics) */
    public /* synthetic */ AutoGeneratedValue(String str, Map map, int i, j jVar) {
        this((i & 1) != 0 ? null : str, (i & 2) != 0 ? null : map);
    }
}
